### ISSUE TITLE
getTestMonitor does not return a list

### ISSUE THREAD

**Issue by lucacavazzana** [Neotys-Labs/neoload-web-java-client#1]
According the [NeoLoad API](https://neoload-api.saas.neotys.com/explore/#/) the call to `GET /tests/{testId}/monitors` is supposed to return a list of counters, while the client maps the response to a single counter ([see doc](https://github.com/Neotys-Labs/neoload-web-java-client/blob/master/docs/ResultsApi.md#getTestMonitors)).

The result is the following error:
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at io.swagger.client.JSON.deserialize(JSON.java:132)
	at io.swagger.client.ApiClient.deserialize(ApiClient.java:710)
	at io.swagger.client.ApiClient.handleResponse(ApiClient.java:913)
	at io.swagger.client.ApiClient.execute(ApiClient.java:840)
	at io.swagger.client.api.ResultsApi.getTestMonitorsWithHttpInfo(ResultsApi.java:1498)
	at io.swagger.client.api.ResultsApi.getTestMonitors(ResultsApi.java:1484)
	...
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at line 1 column 2 path $
	at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:385)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:213)
	... 34 more
```

**Comment by neotysbde** [comment]
The open API definition is fixed but the java client is not updated yet. You can generate the java client using the last API definition (https://neoload-api.saas.neotys.com/explore/swagger.yaml) and swagger editor as explained here: https://www.neotys.com/documents/doc/nlweb/latest/en/html/#25074.htm.

This project will be updated soon.
